name: Mysite44
favicon: null
layout_spectrum: 0.17570286407135427
typography_spectrum: 0.6429583926219493
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.5708317144308239
  lightness: 0.9795904853381217
  saturation: 0.09283531666733325
  rhythmicContrast: 0.6374529988970608
purpose: []
